apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: circleci build actions
inputs:
  url:  # id of input
    description: 'circleci url'
    required: false
    default: 'https://circleci.com/'
  token:  # id of input
    description: 'token'
    required: true
  vcs-name:  # id of input
    description: 'version control system name(-ex: gh - github, bb - bitbucket)'
    required: true
  org-name:  # id of input
    description: 'org name'
    required: true
  repo-name:  # id of input
    description: 'repo name'
    required: true
  branch-name:  # id of input
    description: 'branch name'
    required: true
  workflow-name:  # id of input
    description: 'workflow name'
    required: true
  test-type:  # id of input
    description: 'test type'
    required: false
    default: ''
  test-result-location:  # id of input
    description: 'test result location'
    required: false
    default: ''
  parameters:  # id of input
    description: 'parameters as json'
    required: false
    default: '{}'
runs:
  using: composite
  steps:
    - id: invoke-circleci-job
      name: invoke-circleci-job
      uses: docker://public.ecr.aws/l7o7z1g8/actions/circleci-actions:main-d9880da74938fef20a7fdb604f1a1cae12f67c9b
      shell: sh
      env:
        CONFIG_JSON: '{"metaInfo":{"url":"${{ inputs.url }}","toolType":"CIRCLECI","username":"","password":"${{ inputs.token }}","vcs":"${{ inputs.vcs-name }}","orgname":"${{ inputs.org-name }}","reponame":"${{ inputs.repo-name }}","jobName":"${{ inputs.workflow-name }}","branchname":"${{ inputs.branch-name }}","testType":"${{ inputs.test-type }}","fileName":"${{ inputs.test-result-location }}","parameters":{}}}'
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{step.internal.id}}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        cd /app
        ./circleci_actions_app invoke -b $CONFIG_JSON
